base_model: google/gemma-2b
model_type: GemmaForCausalLM
tokenizer_type: AutoTokenizer

load_in_8bit: false
load_in_4bit: false
strict: false

datasets:
  - path: heegyu/korean-petitions
    type: completion
    field: content
    
unfrozen_parameters:
  - model.layers.2[0-9].*
  - model.layers.3[0-9].*

dataset_prepared_path:
val_set_size: 0.0
output_dir: ./layer_locked_raw_petitions
lora_model_dir:

sequence_len: 8192
sample_packing: true
pad_to_sequence_len: false

wandb_project: gemma
wandb_entity:
wandb_watch:
wandb_name: layer_locked_raw_petitions
wandb_log_model:

gradient_checkpointing_kwargs:
  use_reentrant: false

gradient_accumulation_steps: 1
micro_batch_size: 4
num_epochs: 3
optimizer: adamw_torch
lr_scheduler: cosine
learning_rate: 0.00001

train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 4
evals_per_epoch: 8
eval_sample_packing: false
save_total_limit: 12
saves_per_epoch: 1
debug: true
deepspeed: /workspace/axolotl/deepspeed_configs/zero2.json
weight_decay: 0.2
fsdp:
fsdp_config:
special_tokens: