base_model: beomi/Llama-3-Open-Ko-8B
model_type: LlamaForCausalLM
tokenizer_type: AutoTokenizer

load_in_8bit: false
load_in_4bit: false
strict: false

datasets:
  - path: sieu-n/korean-newstext-dump
    type: completion
    field: text
    
unfrozen_parameters:
  - model.layers.0.input_layernorm.weight
  - model.layers.0.mlp.down_proj.weight
  - model.layers.0.mlp.gate_proj.weight
  - model.layers.0.mlp.up_proj.weight
  - model.layers.0.post_attention_layernorm.weight
  - model.layers.0.self_attn.k_proj.weight
  - model.layers.0.self_attn.o_proj.weight
  - model.layers.0.self_attn.q_proj.weight
  - model.layers.0.self_attn.v_proj.weight
  - model.layers.1.input_layernorm.weight
  - model.layers.1.mlp.down_proj.weight
  - model.layers.1.mlp.gate_proj.weight
  - model.layers.1.mlp.up_proj.weight
  - model.layers.1.post_attention_layernorm.weight
  - model.layers.1.self_attn.k_proj.weight
  - model.layers.1.self_attn.o_proj.weight
  - model.layers.1.self_attn.q_proj.weight
  - model.layers.1.self_attn.v_proj.weight
  - model.layers.2.input_layernorm.weight
  - model.layers.2.mlp.down_proj.weight
  - model.layers.2.mlp.gate_proj.weight
  - model.layers.2.mlp.up_proj.weight
  - model.layers.2.post_attention_layernorm.weight
  - model.layers.2.self_attn.k_proj.weight
  - model.layers.2.self_attn.o_proj.weight
  - model.layers.2.self_attn.q_proj.weight
  - model.layers.2.self_attn.v_proj.weight
  - model.layers.3.input_layernorm.weight
  - model.layers.3.mlp.down_proj.weight
  - model.layers.3.mlp.gate_proj.weight
  - model.layers.3.mlp.up_proj.weight
  - model.layers.3.post_attention_layernorm.weight
  - model.layers.3.self_attn.k_proj.weight
  - model.layers.3.self_attn.o_proj.weight
  - model.layers.3.self_attn.q_proj.weight
  - model.layers.3.self_attn.v_proj.weight
  - model.layers.4.input_layernorm.weight
  - model.layers.4.mlp.down_proj.weight
  - model.layers.4.mlp.gate_proj.weight
  - model.layers.4.mlp.up_proj.weight
  - model.layers.4.post_attention_layernorm.weight
  - model.layers.4.self_attn.k_proj.weight
  - model.layers.4.self_attn.o_proj.weight
  - model.layers.4.self_attn.q_proj.weight
  - model.layers.4.self_attn.v_proj.weight
  - model.layers.5.input_layernorm.weight
  - model.layers.5.mlp.down_proj.weight
  - model.layers.5.mlp.gate_proj.weight
  - model.layers.5.mlp.up_proj.weight
  - model.layers.5.post_attention_layernorm.weight
  - model.layers.5.self_attn.k_proj.weight
  - model.layers.5.self_attn.o_proj.weight
  - model.layers.5.self_attn.q_proj.weight
  - model.layers.5.self_attn.v_proj.weight
  - model.layers.6.input_layernorm.weight
  - model.layers.6.mlp.down_proj.weight
  - model.layers.6.mlp.gate_proj.weight
  - model.layers.6.mlp.up_proj.weight
  - model.layers.6.post_attention_layernorm.weight
  - model.layers.6.self_attn.k_proj.weight
  - model.layers.6.self_attn.o_proj.weight
  - model.layers.6.self_attn.q_proj.weight
  - model.layers.6.self_attn.v_proj.weight
  - model.layers.7.input_layernorm.weight
  - model.layers.7.mlp.down_proj.weight
  - model.layers.7.mlp.gate_proj.weight
  - model.layers.7.mlp.up_proj.weight
  - model.layers.7.post_attention_layernorm.weight
  - model.layers.7.self_attn.k_proj.weight
  - model.layers.7.self_attn.o_proj.weight
  - model.layers.7.self_attn.q_proj.weight
  - model.layers.7.self_attn.v_proj.weight
  - model.layers.8.input_layernorm.weight
  - model.layers.8.mlp.down_proj.weight
  - model.layers.8.mlp.gate_proj.weight
  - model.layers.8.mlp.up_proj.weight
  - model.layers.8.post_attention_layernorm.weight
  - model.layers.8.self_attn.k_proj.weight
  - model.layers.8.self_attn.o_proj.weight
  - model.layers.8.self_attn.q_proj.weight
  - model.layers.8.self_attn.v_proj.weight
  - model.layers.9.input_layernorm.weight
  - model.layers.9.mlp.down_proj.weight
  - model.layers.9.mlp.gate_proj.weight
  - model.layers.9.mlp.up_proj.weight
  - model.layers.9.post_attention_layernorm.weight
  - model.layers.9.self_attn.k_proj.weight
  - model.layers.9.self_attn.o_proj.weight
  - model.layers.9.self_attn.q_proj.weight
  - model.layers.9.self_attn.v_proj.weight
  - model.layers.10.input_layernorm.weight
  - model.layers.10.mlp.down_proj.weight
  - model.layers.10.mlp.gate_proj.weight
  - model.layers.10.mlp.up_proj.weight
  - model.layers.10.post_attention_layernorm.weight
  - model.layers.10.self_attn.k_proj.weight
  - model.layers.10.self_attn.o_proj.weight
  - model.layers.10.self_attn.q_proj.weight
  - model.layers.10.self_attn.v_proj.weight
  - model.layers.11.input_layernorm.weight
  - model.layers.11.mlp.down_proj.weight
  - model.layers.11.mlp.gate_proj.weight
  - model.layers.11.mlp.up_proj.weight
  - model.layers.11.post_attention_layernorm.weight
  - model.layers.11.self_attn.k_proj.weight
  - model.layers.11.self_attn.o_proj.weight
  - model.layers.11.self_attn.q_proj.weight
  - model.layers.11.self_attn.v_proj.weight
  - model.layers.12.input_layernorm.weight
  - model.layers.12.mlp.down_proj.weight
  - model.layers.12.mlp.gate_proj.weight
  - model.layers.12.mlp.up_proj.weight
  - model.layers.12.post_attention_layernorm.weight
  - model.layers.12.self_attn.k_proj.weight
  - model.layers.12.self_attn.o_proj.weight
  - model.layers.12.self_attn.q_proj.weight
  - model.layers.12.self_attn.v_proj.weight
  - model.layers.13.input_layernorm.weight
  - model.layers.13.mlp.down_proj.weight
  - model.layers.13.mlp.gate_proj.weight
  - model.layers.13.mlp.up_proj.weight
  - model.layers.13.post_attention_layernorm.weight
  - model.layers.13.self_attn.k_proj.weight
  - model.layers.13.self_attn.o_proj.weight
  - model.layers.13.self_attn.q_proj.weight
  - model.layers.13.self_attn.v_proj.weight
  - model.layers.14.input_layernorm.weight
  - model.layers.14.mlp.down_proj.weight
  - model.layers.14.mlp.gate_proj.weight
  - model.layers.14.mlp.up_proj.weight
  - model.layers.14.post_attention_layernorm.weight
  - model.layers.14.self_attn.k_proj.weight
  - model.layers.14.self_attn.o_proj.weight
  - model.layers.14.self_attn.q_proj.weight
  - model.layers.14.self_attn.v_proj.weight
  - model.layers.15.input_layernorm.weight
  - model.layers.15.mlp.down_proj.weight
  - model.layers.15.mlp.gate_proj.weight
  - model.layers.15.mlp.up_proj.weight
  - model.layers.15.post_attention_layernorm.weight
  - model.layers.15.self_attn.k_proj.weight
  - model.layers.15.self_attn.o_proj.weight
  - model.layers.15.self_attn.q_proj.weight
  - model.layers.15.self_attn.v_proj.weight
  - model.layers.16.input_layernorm.weight
  - model.layers.16.mlp.down_proj.weight
  - model.layers.16.mlp.gate_proj.weight
  - model.layers.16.mlp.up_proj.weight
  - model.layers.16.post_attention_layernorm.weight
  - model.layers.16.self_attn.k_proj.weight
  - model.layers.16.self_attn.o_proj.weight
  - model.layers.16.self_attn.q_proj.weight
  - model.layers.16.self_attn.v_proj.weight
  - model.layers.17.input_layernorm.weight
  - model.layers.17.mlp.down_proj.weight
  - model.layers.17.mlp.gate_proj.weight
  - model.layers.17.mlp.up_proj.weight
  - model.layers.17.post_attention_layernorm.weight
  - model.layers.17.self_attn.k_proj.weight
  - model.layers.17.self_attn.o_proj.weight
  - model.layers.17.self_attn.q_proj.weight
  - model.layers.17.self_attn.v_proj.weight
  - model.layers.18.input_layernorm.weight
  - model.layers.18.mlp.down_proj.weight
  - model.layers.18.mlp.gate_proj.weight
  - model.layers.18.mlp.up_proj.weight
  - model.layers.18.post_attention_layernorm.weight
  - model.layers.18.self_attn.k_proj.weight
  - model.layers.18.self_attn.o_proj.weight
  - model.layers.18.self_attn.q_proj.weight
  - model.layers.18.self_attn.v_proj.weight
  - model.layers.19.input_layernorm.weight
  - model.layers.19.mlp.down_proj.weight
  - model.layers.19.mlp.gate_proj.weight
  - model.layers.19.mlp.up_proj.weight
  - model.layers.19.post_attention_layernorm.weight
  - model.layers.19.self_attn.k_proj.weight
  - model.layers.19.self_attn.o_proj.weight
  - model.layers.19.self_attn.q_proj.weight
  - model.layers.19.self_attn.v_proj.weight
  - model.layers.20.input_layernorm.weight
  - model.layers.20.mlp.down_proj.weight
  - model.layers.20.mlp.gate_proj.weight
  - model.layers.20.mlp.up_proj.weight
  - model.layers.20.post_attention_layernorm.weight
  - model.layers.20.self_attn.k_proj.weight
  - model.layers.20.self_attn.o_proj.weight
  - model.layers.20.self_attn.q_proj.weight
  - model.layers.20.self_attn.v_proj.weight
  - model.layers.21.input_layernorm.weight
  - model.layers.21.mlp.down_proj.weight
  - model.layers.21.mlp.gate_proj.weight
  - model.layers.21.mlp.up_proj.weight
  - model.layers.21.post_attention_layernorm.weight
  - model.layers.21.self_attn.k_proj.weight
  - model.layers.21.self_attn.o_proj.weight
  - model.layers.21.self_attn.q_proj.weight
  - model.layers.21.self_attn.v_proj.weight
  - model.layers.22.input_layernorm.weight
  - model.layers.22.mlp.down_proj.weight
  - model.layers.22.mlp.gate_proj.weight
  - model.layers.22.mlp.up_proj.weight
  - model.layers.22.post_attention_layernorm.weight
  - model.layers.22.self_attn.k_proj.weight
  - model.layers.22.self_attn.o_proj.weight
  - model.layers.22.self_attn.q_proj.weight
  - model.layers.22.self_attn.v_proj.weight
  - model.layers.23.input_layernorm.weight
  - model.layers.23.mlp.down_proj.weight
  - model.layers.23.mlp.gate_proj.weight
  - model.layers.23.mlp.up_proj.weight
  - model.layers.23.post_attention_layernorm.weight
  - model.layers.23.self_attn.k_proj.weight
  - model.layers.23.self_attn.o_proj.weight
  - model.layers.23.self_attn.q_proj.weight
  - model.layers.23.self_attn.v_proj.weight
  - model.layers.24.input_layernorm.weight
  - model.layers.24.mlp.down_proj.weight
  - model.layers.24.mlp.gate_proj.weight
  - model.layers.24.mlp.up_proj.weight
  - model.layers.24.post_attention_layernorm.weight
  - model.layers.24.self_attn.k_proj.weight
  - model.layers.24.self_attn.o_proj.weight
  - model.layers.24.self_attn.q_proj.weight
  - model.layers.24.self_attn.v_proj.weight
  - model.layers.25.input_layernorm.weight
  - model.layers.25.mlp.down_proj.weight
  - model.layers.25.mlp.gate_proj.weight
  - model.layers.25.mlp.up_proj.weight
  - model.layers.25.post_attention_layernorm.weight
  - model.layers.25.self_attn.k_proj.weight
  - model.layers.25.self_attn.o_proj.weight
  - model.layers.25.self_attn.q_proj.weight
  - model.layers.25.self_attn.v_proj.weight
  - model.layers.26.input_layernorm.weight
  - model.layers.26.mlp.down_proj.weight
  - model.layers.26.mlp.gate_proj.weight
  - model.layers.26.mlp.up_proj.weight
  - model.layers.26.post_attention_layernorm.weight
  - model.layers.26.self_attn.k_proj.weight
  - model.layers.26.self_attn.o_proj.weight
  - model.layers.26.self_attn.q_proj.weight
  - model.layers.26.self_attn.v_proj.weight
  - model.layers.27.input_layernorm.weight
  - model.layers.27.mlp.down_proj.weight
  - model.layers.27.mlp.gate_proj.weight
  - model.layers.27.mlp.up_proj.weight
  - model.layers.27.post_attention_layernorm.weight
  - model.layers.27.self_attn.k_proj.weight
  - model.layers.27.self_attn.o_proj.weight
  - model.layers.27.self_attn.q_proj.weight
  - model.layers.27.self_attn.v_proj.weight

dataset_prepared_path:
val_set_size: 0.0
output_dir: ./llama3-20240427-experimental-layer-locked-raw
lora_model_dir:

sequence_len: 4096
sample_packing: true
pad_to_sequence_len: false

wandb_project: 1_raw_instructions
wandb_entity:
wandb_watch:
wandb_name: llama3-20240427-experimental-layer-locked-raw
wandb_log_model:

gradient_checkpointing_kwargs:
  use_reentrant: false

gradient_accumulation_steps: 1
micro_batch_size: 4
num_epochs: 3
optimizer: adamw_torch
lr_scheduler: cosine
learning_rate: 0.00001

train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 4
evals_per_epoch: 8
eval_sample_packing: false
save_total_limit: 12
saves_per_epoch: 1
debug: true
# deepspeed: /workspace/axolotl/deepspeed_configs/zero2.json
weight_decay: 0.2
fsdp:
fsdp_config:
special_tokens:
  pad_token: "[PAD]"