base_model: beomi/Llama-3-Open-Ko-8B
model_type: LlamaForCausalLM
tokenizer_type: AutoTokenizer

load_in_8bit: false
load_in_4bit: false
strict: false

datasets:
  - path: sigridjineth/instructions-ko-small
    type: sharegpt
    conversation: chatml
    
unfrozen_parameters:
  - model.layers.28.*
  - model.layers.29.*
  - model.layers.30.*
  - model.layers.31.*

dataset_prepared_path:
val_set_size: 0.001
output_dir: ./llama3-20240427-experimental-layer-locked-inst
lora_model_dir:

sequence_len: 4096
sample_packing: false
pad_to_sequence_len: false

wandb_project: 1_raw_instructions
wandb_entity:
wandb_watch:
wandb_name: llama3-20240427-experimental-layer-locked-inst
wandb_log_model:

gradient_checkpointing_kwargs:
  use_reentrant: false

gradient_accumulation_steps: 16
micro_batch_size: 8
num_epochs: 3
optimizer: adamw_torch
lr_scheduler: cosine
learning_rate: 0.00004

train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 10
evals_per_epoch: 8
eval_sample_packing: false
save_total_limit: 12
saves_per_epoch: 2
debug: true
# deepspeed: ./axolotl/deepspeed_configs/zero2.json
weight_decay: 0
fsdp:
fsdp_config:
special_tokens:
